export const BOOK_LIST_LOAD = "BOOK_LIST_LOAD";
export const BOOK_LIST_SUCCESS = "BOOK_LIST_SUCCESS";
export const BOOK_LIST_ERROR = "BOOK_LIST_ERROR";

export const AUTHOR_LIST_LOAD = "AUTHOR_LIST_LOAD";
export const AUTHOR_LIST_SUCCESS = "AUTHOR_LIST_SUCCESS";
export const AUTHOR_LIST_ERROR = "AUTHOR_LIST_ERROR";

export const CATEGORY_LIST_LOAD = "CATEGORY_LIST_LOAD";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_ERROR = "CATEGORY_LIST_ERROR";

export const AUTHOR_CATEGORY_LOAD = "AUTHOR_CATEGORY_LOAD";
export const AUTHOR_CATEGORY_SUCCESS = "AUTHOR_CATEGORY_SUCCESS";
export const AUTHOR_CATEGORY_ERROR = "AUTHOR_CATEGORY_ERROR";

export const BOOK_FILTER_LOAD = "BOOK_FILTER_LOAD";
export const BOOK_FILTER_SUCCESS = "BOOK_FILTER_SUCCESS";
export const BOOK_FILTER_ERROR = "BOOK_FILTER_ERROR";
